export const LOCATIONS = [
  "Abandoned Space Station",
  "Secret Laboratory",
  "Mafia Wedding",
  "Luxury Cruise",
  "Underground Bunker",
  "Military Base",
  "Illegal Casino",
  "Private Island",
  "VIP Party",
  "Interrogation Room",
  "Operating Room",
  "Haunted Hotel",
  "Hackathon",
  "Desert Music Festival",
  "Airport Security Room",
  "Bank Vault",
  "Movie Set",
  "Research Base in Antarctica",
  "High-Tech Startup Office",
  "Prison",
  "Harel's Apartment",
  "College of Management",
  "Student Housing",
  "Outdoor Party",
  "Prague",
  "Sea of Galilee",
  "Eilat",
] as const;
